---
# file: roles/nginx-repo/tasks/main.yml

# Install the Nginx RPM repository

- name: nginx-repo | Installing nginx-release RPM
  yum: name={{ nginx_release_rpm }} state=present disable_gpg_check=yes
  register: nginx_release

- name: nginx-repo | Adding nginx repo file
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644
